version: '3.9'
services:
  api:
    platform: linux/amd64
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    env_file:
      - ./api/.env
    ports:
      - 8080:8080
  client:
    platform: linux/amd64
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    env_file:
      - ./client/.env
    ports:
      - 3000:3000
