version: '3.9'
services:
  api:
    platform: linux/amd64
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    env_file:
      - ./api/.env
    ports:
      - 8080:8080

  # client:
  #   platform: linux/amd64
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./client:/app
  #   environment:
  #     - NODE_ENV=production
  #   env_file:
  #     - ./client/.env
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - api
  front:
    platform: linux/amd64
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
    env_file:
      - ./front/.env
    ports:
      - 3000:3000
    depends_on:
      - api
