version: '3.9'
services:
  api:
    platform: linux/amd64
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    env_file:
      - ./api/.env
    ports:
      - 8080:8080

  front:
    platform: linux/amd64
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
    env_file:
      - ./front/.env
    ports:
      - 3000:3000
    depends_on:
      - api

  web:
    platform: linux/amd64
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - front
