version: '3.7'
services:
  api:
    image: miyatto/js-college-api
    ports:
      - 8080:3000
    networks:
      - webnet
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - webnet
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
networks:
  webnet:
